load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "controlplane",
    srcs = [
        "apigateway_controller.go",
        "auth_filters.go",
        "cors.go",
        "endpoints.go",
        "filters.go",
        "gotrue.go",
        "logging.go",
        "pg-meta.go",
        "postgrest.go",
        "snapshot.go",
        "storage.go",
        "studio.go",
        "utils.go",
    ],
    importpath = "code.icb4dc0.de/prskr/supabase-operator/internal/controlplane",
    visibility = ["//:__subpackages__"],
    deps = [
        "//api/v1alpha1",
        "//internal/meta",
        "//internal/supabase",
        "@com_github_envoyproxy_go_control_plane//pkg/cache/types",
        "@com_github_envoyproxy_go_control_plane//pkg/cache/v3:cache",
        "@com_github_envoyproxy_go_control_plane//pkg/resource/v3:resource",
        "@com_github_envoyproxy_go_control_plane_envoy//config/accesslog/v3:accesslog",
        "@com_github_envoyproxy_go_control_plane_envoy//config/cluster/v3:cluster",
        "@com_github_envoyproxy_go_control_plane_envoy//config/core/v3:core",
        "@com_github_envoyproxy_go_control_plane_envoy//config/endpoint/v3:endpoint",
        "@com_github_envoyproxy_go_control_plane_envoy//config/listener/v3:listener",
        "@com_github_envoyproxy_go_control_plane_envoy//config/rbac/v3:rbac",
        "@com_github_envoyproxy_go_control_plane_envoy//config/route/v3:route",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/access_loggers/stream/v3:stream",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/filters/http/basic_auth/v3:basic_auth",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/filters/http/cors/v3:cors",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/filters/http/jwt_authn/v3:jwt_authn",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/filters/http/oauth2/v3:oauth2",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/filters/http/rbac/v3:rbac",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/filters/http/router/v3:router",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/filters/network/http_connection_manager/v3:http_connection_manager",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/transport_sockets/tls/v3:tls",
        "@com_github_envoyproxy_go_control_plane_envoy//type/matcher/v3:matcher",
        "@com_github_envoyproxy_go_control_plane_envoy//type/v3:type",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_api//discovery/v1:discovery",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/types",
        "@io_k8s_sigs_controller_runtime//:controller-runtime",
        "@io_k8s_sigs_controller_runtime//pkg/builder",
        "@io_k8s_sigs_controller_runtime//pkg/client",
        "@io_k8s_sigs_controller_runtime//pkg/controller/controllerutil",
        "@io_k8s_sigs_controller_runtime//pkg/handler",
        "@io_k8s_sigs_controller_runtime//pkg/log",
        "@io_k8s_sigs_controller_runtime//pkg/predicate",
        "@io_k8s_sigs_controller_runtime//pkg/reconcile",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_google_protobuf//types/known/structpb",
    ],
)
