site_name: Supabase Operator
site_url: https://docs.supabase-operator.icb4dc0.de/
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - toc.integrate

plugins:
  - search
  - kroki:
      HttpMethod: POST

nav:
  - Home:
      - About: index.md
      - Getting Started: getting_started.md
  - Components:
      - Overview: components/overview.md
      - Core: components/core.md
  - API Reference: api/supabase.k8s.icb4dc0.de.md
