site_name: Supabase Operator
site_author: Peter Kurfer
site_url: https://prskr.github.io/supabase-operator/
site_description: |
  Documentation for the Supabase Operator, a Kubernetes operator for managing Supabase instances.
repo_name: prskr/supabase-operator
repo_url: https://github.com/prskr/supabase-operator
dev_addr: "127.0.0.1:8001"
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.code.copy
    - content.footnote.tooltips
plugins:
  - search
  - kroki:
      HttpMethod: POST
nav:
  - Home:
      - About: index.md
      - Getting Started: getting_started.md
  - Components:
      - Overview: components/overview.md
      - Core: components/core.md
      - APIGateway: components/apigateway.md
  - Auth:
      - Overview: auth/overview.md
      - Email: auth/email.md
      - Social Providers:
          - Azure: auth/providers/azure.md
  - Development:
      - Tools: development/tools.md
      - Local Development: development/local_dev.md
      - Studio: development/studio.md
  - API Reference: api/supabase.k8s.icb4dc0.de.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
