"supabase-operator"

module(
    name = "de_icb4dc0_code_prskr_supabase-operator",
)

bazel_dep(
    name = "rules_go",
    version = "0.57.0",
)
bazel_dep(
    name = "gazelle",
    version = "0.45.0",
)
bazel_dep(
    name = "rules_oci",
    version = "2.2.6",
)
bazel_dep(
    name = "platforms",
    version = "1.0.0",
)
bazel_dep(
    name = "rules_pkg",
    version = "1.1.0",
)
bazel_dep(
    name = "aspect_bazel_lib",
    version = "2.21.2",
)
bazel_dep(
    name = "buildifier_prebuilt",
    version = "8.2.0.2",
)
bazel_dep(
    name = "rules_multirun",
    version = "0.13.0",
)

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "kubectl_linux_arm64",
    downloaded_file_path = "kubectl_linux_arm64",
    executable = True,
    sha256 = "48541d119455ac5bcc5043275ccda792371e0b112483aa0b29378439cf6322b9",
    url = "https://dl.k8s.io/release/v1.33.0/bin/linux/arm64/kubectl",
)

http_file(
    name = "kubectl_linux_amd64",
    downloaded_file_path = "kubectl_linux_amd64",
    executable = True,
    sha256 = "9efe8d3facb23e1618cba36fb1c4e15ac9dc3ed5a2c2e18109e4a66b2bac12dc",
    url = "https://dl.k8s.io/release/v1.33.0/bin/linux/amd64/kubectl",
)

http_file(
    name = "kubectl_darwin_arm64",
    downloaded_file_path = "kubectl_darwin_arm64",
    executable = True,
    sha256 = "007746617abc12746dd80ad6c261c2b062269688d44c0b97aa47108c562b07c1",
    url = "https://dl.k8s.io/release/v1.33.0/bin/darwin/arm64/kubectl",
)

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "distroless_base_nossl_debian12",
    digest = "sha256:9a1c8b2ff7412ea80ca8c531eb7542e0e7766c8cf79489a8f0f31f0aa341c0fe",
    image = "gcr.io/distroless/base-nossl-debian12",
    platforms = [
        "linux/amd64",
        "linux/arm64/v8",
    ],
)
use_repo(
    oci,
    "distroless_base_nossl_debian12",
    "distroless_base_nossl_debian12_linux_amd64",
    "distroless_base_nossl_debian12_linux_arm64_v8",
)

go_tool_deps = use_extension("@gazelle//:extensions.bzl", "go_deps", isolate = True)
go_tool_deps.from_file(go_mod = "//tools:go.mod")
use_repo(
    go_tool_deps,
    "io_k8s_sigs_kustomize_kustomize_v5",
)

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.from_file(go_mod = "//:go.mod")
go_sdk.nogo(nogo = "//:nogo")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")

# hack required because otherwise bazel tries to generate necessary proto files and is missing one
# instead of simply using the pre-generated files
go_deps.gazelle_override(
    build_file_generation = "clean",
    directives = [
        "gazelle:exclude **/*.proto",
        "gazelle:go_generate_proto false",
    ],
    path = "sigs.k8s.io/apiserver-network-proxy/konnectivity-client",
)

supabase_compose = use_repo_rule("//build:extensions.bzl", "supabase_compose")

supabase_compose(
    name = "supabase_compose",
    sha256 = "ff44c48a501cf1c18103027b3a8b3b0d2fa51766b35bba38832447f8c4863afd",
    version = "1.25.04",
)

supabase_migrations = use_repo_rule("//build:extensions.bzl", "supabase_migrations")

supabase_migrations(
    name = "supabase_migrations",
    path_prefix = "migrations/db/migrations",
    sha256 = "f3eec4aff82625f66e382662c2ca03d470baac15433e4a2ee7c72efc588ec900",
    version = "15.8.1.131",
)

supabase_migrations(
    name = "supabase_init_scripts",
    path_prefix = "migrations/db/init-scripts",
    sha256 = "f3eec4aff82625f66e382662c2ca03d470baac15433e4a2ee7c72efc588ec900",
    version = "15.8.1.131",
)

use_repo(
    go_deps,
    "cc_mvdan_gofumpt",
    "com_github_alecthomas_assert_v2",
    "com_github_alecthomas_kong",
    "com_github_elastic_crd_ref_docs",
    "com_github_envoyproxy_go_control_plane",
    "com_github_envoyproxy_go_control_plane_envoy",
    "com_github_go_logr_logr",
    "com_github_gordonklaus_ineffassign",
    "com_github_jackc_pgx_v5",
    "com_github_kisielk_errcheck",
    "com_github_lasiar_canonicalheader",
    "com_github_lestrrat_go_jwx_v2",
    "com_github_onsi_ginkgo_v2",
    "com_github_onsi_gomega",
    "com_github_prometheus_operator_prometheus_operator_pkg_apis_monitoring",
    "com_github_sivchari_containedctx",
    "com_github_stretchr_testify",
    "de_icb4dc0_code_prskr_bazel_golangci_lint_analyzers",
    "in_gopkg_yaml_v3",
    "io_k8s_api",
    "io_k8s_apimachinery",
    "io_k8s_client_go",
    "io_k8s_sigs_controller_runtime",
    "io_k8s_sigs_controller_runtime_tools_setup_envtest",
    "io_k8s_sigs_controller_tools",
    "org_golang_google_grpc",
    "org_golang_google_protobuf",
    "org_golang_x_exp",
    "org_uber_go_nilaway",
    "org_uber_go_zap",
)
