load("@rules_multirun//:defs.bzl", "command", "multirun")
load("@rules_oci//oci:defs.bzl", "oci_push")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("//build:kubectl.bzl", "kubectl_apply")

sh_binary(
    name = "start_cluster",
    srcs = ["setup_dev_cluster.sh"],
    args = [
        "$(rootpath @io_k8s_sigs_kind//:kind)",
        "$(rootpath @multitool//tools/kubectl:kubectl)",
        "$(rootpath :cluster.yaml)",
    ],
    data = [
        "cluster.yaml",
        "@io_k8s_sigs_kind//:kind",
        "@multitool//tools/kubectl",
    ],
)

sh_binary(
    name = "teardown_cluster",
    srcs = ["teardown_dev_cluster.sh"],
    args = [
        "$(rootpath @io_k8s_sigs_kind//:kind)",
    ],
    data = [
        "@io_k8s_sigs_kind//:kind",
    ],
)

genrule(
    name = "dev-manifest",
    srcs = [
        "//:image_arm64.digest",
        "//config:all",
    ],
    outs = ["manifests.yaml"],
    cmd = """
    image_digest=`cat ./$(execpath //:image_arm64.digest)`
    cd config/dev
    ../../$(execpath @io_k8s_sigs_kustomize_kustomize_v5//:v5) edit set image "controller=localhost:5005/supabase-operator:latest@$$image_digest"
    cd ../../
    $(execpath @io_k8s_sigs_kustomize_kustomize_v5//:v5) build ./config/dev > $@
    """,
    local = True,
    tools = ["@io_k8s_sigs_kustomize_kustomize_v5//:v5"],
)

kubectl_apply(
    name = "apply-dev-manifest",
    context = "kind-supabase-operator-debug",
    kubectl = "@multitool//tools/kubectl:kubectl",
    manifest = ":dev-manifest",
)

oci_push(
    name = "push_local",
    image = "//:image_arm64",
    remote_tags = "//:image_arm64.digest",
    repository = "localhost:5005/supabase-operator",
)

command(
    name = "apply_kustomization",
    command = ":apply-dev-manifest",
)

command(
    name = "push_controller_image",
    command = ":push_local",
)

multirun(
    name = "dev",
    commands = [
        ":apply_kustomization",
        ":push_controller_image",
    ],
    jobs = 0,
)
