load("@rules_go//go:def.bzl", "go_library", "go_test")

filegroup(
    name = "reconciler_src",
    srcs = glob(["*.go"]),
    visibility = ["//:__subpackages__"],
)

go_library(
    name = "controller",
    srcs = [
        "apigateway_controller.go",
        "core_db_controller.go",
        "core_gotrue_controller.go",
        "core_jwt_controller.go",
        "core_postgrest_controller.go",
        "dashboard_pg-meta_controller.go",
        "dashboard_studio_controller.go",
        "object_meta.go",
        "permissions.go",
        "storage_api_controller.go",
        "storage_imgproxy_controller.go",
        "storage_s3_creds_controller.go",
        "utils.go",
    ],
    embedsrcs = ["templates/envoy_control_plane_config.yaml.tmpl"],
    importpath = "github.com/prskr/supabase-operator/internal/controller",
    visibility = ["//:__subpackages__"],
    deps = [
        "//api",
        "//api/v1alpha1",
        "//assets/migrations",
        "//internal/certs",
        "//internal/db",
        "//internal/errx",
        "//internal/jwk",
        "//internal/meta",
        "//internal/pw",
        "//internal/supabase",
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_lestrrat_go_jwx_v2//jwa",
        "@com_github_lestrrat_go_jwx_v2//jwt",
        "@com_github_prometheus_operator_prometheus_operator_pkg_apis_monitoring//v1:monitoring",
        "@io_k8s_api//apps/v1:apps",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/api/resource",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/fields",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/types",
        "@io_k8s_apimachinery//pkg/util/intstr",
        "@io_k8s_client_go//tools/events",
        "@io_k8s_sigs_controller_runtime//:controller-runtime",
        "@io_k8s_sigs_controller_runtime//pkg/builder",
        "@io_k8s_sigs_controller_runtime//pkg/client",
        "@io_k8s_sigs_controller_runtime//pkg/controller/controllerutil",
        "@io_k8s_sigs_controller_runtime//pkg/handler",
        "@io_k8s_sigs_controller_runtime//pkg/log",
        "@io_k8s_sigs_controller_runtime//pkg/predicate",
        "@io_k8s_sigs_controller_runtime//pkg/reconcile",
    ],
)

go_test(
    name = "controller_test",
    srcs = [
        "apigateway_controller_test.go",
        "common_test.go",
        "core_db_controller_test.go",
        "dashboard_studio_controller_test.go",
        "storage_api_controller_test.go",
        "storage_s3_creds_controller_test.go",
        "suite_test.go",
    ],
    data = ["//config/crd/bases:crd_bases"] + glob(["testdata/**"]),
    embed = [":controller"],
    deps = [
        "//api/v1alpha1",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
        "@com_github_stretchr_testify//assert",
        "@io_k8s_api//apps/v1:apps",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/api/errors",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/types",
        "@io_k8s_apimachinery//pkg/util/intstr",
        "@io_k8s_apimachinery//pkg/util/runtime",
        "@io_k8s_client_go//kubernetes/scheme",
        "@io_k8s_client_go//rest",
        "@io_k8s_sigs_controller_runtime//pkg/client",
        "@io_k8s_sigs_controller_runtime//pkg/client/fake",
        "@io_k8s_sigs_controller_runtime//pkg/envtest",
        "@io_k8s_sigs_controller_runtime//pkg/log",
        "@io_k8s_sigs_controller_runtime//pkg/log/zap",
        "@io_k8s_sigs_controller_runtime//pkg/reconcile",
    ],
)
