load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_go//go:def.bzl", "go_library", "go_test")

INIT_SCRIPTS = [
    "init-scripts/00000000000000-initial-schema.sql",
    "init-scripts/00000000000001-auth-schema.sql",
    "init-scripts/00000000000002-storage-schema.sql",
    "init-scripts/00000000000003-post-setup.sql",
]

MIGRATION_SCRIPTS = [
    "migrations/20211115181400_update-auth-permissions.sql",
    "migrations/20211118015519_create-realtime-schema.sql",
    "migrations/20211122051245_update-realtime-permissions.sql",
    "migrations/20211124212715_update-auth-owner.sql",
    "migrations/20211130151719_update-realtime-permissions.sql",
    "migrations/20220118070449_enable-safeupdate-postgrest.sql",
    "migrations/20220126121436_finer-postgrest-triggers.sql",
    "migrations/20220224211803_fix-postgrest-supautils.sql",
    "migrations/20220317095840_pg_graphql.sql",
    "migrations/20220321174452_fix-postgrest-alter-type-event-trigger.sql",
    "migrations/20220322085208_gotrue-session-limit.sql",
    "migrations/20220404205710_pg_graphql-on-by-default.sql",
    "migrations/20220609081115_grant-supabase-auth-admin-and-supabase-storage-admin-to-postgres.sql",
    "migrations/20220613123923_pg_graphql-pg-dump-perms.sql",
    "migrations/20220713082019_pg_cron-pg_net-temp-perms-fix.sql",
    "migrations/20221028101028_set_authenticator_timeout.sql",
    "migrations/20221103090837_revoke_admin.sql",
    "migrations/20221207154255_create_pgsodium_and_vault.sql",
    "migrations/20230201083204_grant_auth_roles_to_postgres.sql",
    "migrations/20230224042246_grant_extensions_perms_for_postgres.sql",
    "migrations/20230306081037_grant_pg_monitor_to_postgres.sql",
    "migrations/20230327032006_grant_auth_roles_to_supabase_storage_admin.sql",
    "migrations/20230529180330_alter_api_roles_for_inherit.sql",
    "migrations/20231013070755_grant_authenticator_to_supabase_storage_admin.sql",
    "migrations/20231017062225_grant_pg_graphql_permissions_for_custom_roles.sql",
    "migrations/20231020085357_revoke_writes_on_cron_job_from_postgres.sql",
    "migrations/20231130133139_set_lock_timeout_to_authenticator_role.sql",
    "migrations/20240124080435_alter_lo_export_lo_import_owner.sql",
    "migrations/20240606060239_grant_predefined_roles_to_postgres.sql",
    "migrations/20241031003909_create_orioledb.sql",
    "migrations/20241215003910_backfill_pgmq_metadata.sql",
    "migrations/20250205060043_disable_log_statement_on_internal_roles.sql",
    "migrations/20250205144616_move_orioledb_to_extensions_schema.sql",
    "migrations/20250218031949_pgsodium_mask_role.sql",
    "migrations/20250220051611_pg_net_perms_fix.sql",
    "migrations/20250402065937_alter_internal_event_triggers_owner_to_supabase_admin.sql",
    "migrations/20250402093753_grant_subscription_to_postgres_16_and_above.sql",
    "migrations/20250605172253_grant_with_admin_to_postgres_16_and_above.sql",
    "migrations/20250623125453_tmp_grant_storage_tables_to_postgres_with_grant_option.sql",
    "migrations/20250709135250_grant_storage_schema_to_postgres_with_grant_option.sql",
    "migrations/20250710151649_supabase_read_only_user_default_transaction_read_only.sql",
]

genrule(
    name = "init_scripts",
    srcs = ["@supabase_init_scripts"],
    outs = INIT_SCRIPTS,
    cmd = """
    mkdir -p \"$(@D)/init-scripts/\"
    cp -rf $(locations @supabase_init_scripts//:supabase_init_scripts) \"$(@D)/init-scripts/\"

    grep -ril "ON DATABASE postgres" \"$(@D)/init-scripts/\" | xargs -I {} perl -pi -e 's/ON DATABASE postgres/ON DATABASE {{ .DbName }}/gi' {}
    """,
)

genrule(
    name = "migration_scripts",
    srcs = ["@supabase_migrations"],
    outs = MIGRATION_SCRIPTS,
    cmd = """
    mkdir -p \"$(@D)/migrations/\"
    cp -rf $(locations @supabase_migrations//:supabase_migrations) \"$(@D)/migrations/\"
    ignored=("10000000000000_demote-postgres.sql" "20250312095419_pgbouncer_ownership.sql" "20250417190610_update_pgbouncer_get_auth.sql" "20250421084701_revoke_admin_roles_from_postgres.sql")
    for file in "$${ignored[@]}"; do
    rm -f \"$(@D)/migrations/$$file\"
    done
    """,
)

write_source_files(
    name = "update_migration_scripts",
    diff_test = False,
    files = {f: f for f in INIT_SCRIPTS + MIGRATION_SCRIPTS},
)

go_library(
    name = "migrations",
    srcs = ["migrations.go"],
    embedsrcs = [
        "roles/supabase_functions_admin.sql",
        "setup/realtime.sql",
        "init-scripts/00000000000000-initial-schema.sql",
        "init-scripts/00000000000001-auth-schema.sql",
        "init-scripts/00000000000002-storage-schema.sql",
        "init-scripts/00000000000003-post-setup.sql",
        "migrations/20211115181400_update-auth-permissions.sql",
        "migrations/20211118015519_create-realtime-schema.sql",
        "migrations/20211122051245_update-realtime-permissions.sql",
        "migrations/20211124212715_update-auth-owner.sql",
        "migrations/20211130151719_update-realtime-permissions.sql",
        "migrations/20220118070449_enable-safeupdate-postgrest.sql",
        "migrations/20220126121436_finer-postgrest-triggers.sql",
        "migrations/20220224211803_fix-postgrest-supautils.sql",
        "migrations/20220317095840_pg_graphql.sql",
        "migrations/20220321174452_fix-postgrest-alter-type-event-trigger.sql",
        "migrations/20220322085208_gotrue-session-limit.sql",
        "migrations/20220404205710_pg_graphql-on-by-default.sql",
        "migrations/20220609081115_grant-supabase-auth-admin-and-supabase-storage-admin-to-postgres.sql",
        "migrations/20220613123923_pg_graphql-pg-dump-perms.sql",
        "migrations/20220713082019_pg_cron-pg_net-temp-perms-fix.sql",
        "migrations/20221028101028_set_authenticator_timeout.sql",
        "migrations/20221103090837_revoke_admin.sql",
        "migrations/20221207154255_create_pgsodium_and_vault.sql",
        "migrations/20230201083204_grant_auth_roles_to_postgres.sql",
        "migrations/20230224042246_grant_extensions_perms_for_postgres.sql",
        "migrations/20230306081037_grant_pg_monitor_to_postgres.sql",
        "migrations/20230327032006_grant_auth_roles_to_supabase_storage_admin.sql",
        "migrations/20230529180330_alter_api_roles_for_inherit.sql",
        "migrations/20231013070755_grant_authenticator_to_supabase_storage_admin.sql",
        "migrations/20231017062225_grant_pg_graphql_permissions_for_custom_roles.sql",
        "migrations/20231020085357_revoke_writes_on_cron_job_from_postgres.sql",
        "migrations/20231130133139_set_lock_timeout_to_authenticator_role.sql",
        "migrations/20240124080435_alter_lo_export_lo_import_owner.sql",
        "migrations/20240606060239_grant_predefined_roles_to_postgres.sql",
        "migrations/20241031003909_create_orioledb.sql",
        "migrations/20241215003910_backfill_pgmq_metadata.sql",
        "migrations/20250205060043_disable_log_statement_on_internal_roles.sql",
        "migrations/20250205144616_move_orioledb_to_extensions_schema.sql",
        "migrations/20250218031949_pgsodium_mask_role.sql",
        "migrations/20250220051611_pg_net_perms_fix.sql",
        "migrations/20250402065937_alter_internal_event_triggers_owner_to_supabase_admin.sql",
        "migrations/20250402093753_grant_subscription_to_postgres_16_and_above.sql",
        "migrations/20250605172253_grant_with_admin_to_postgres_16_and_above.sql",
        "migrations/20250623125453_tmp_grant_storage_tables_to_postgres_with_grant_option.sql",
        "migrations/20250709135250_grant_storage_schema_to_postgres_with_grant_option.sql",
        "migrations/20250710151649_supabase_read_only_user_default_transaction_read_only.sql",
    ],
    importpath = "github.com/prskr/supabase-operator/assets/migrations",
    visibility = ["//visibility:public"],
)

go_test(
    name = "migrations_test",
    srcs = ["migrations_test.go"],
    deps = [
        ":migrations",
        "@com_github_alecthomas_assert_v2//:assert",
    ],
)
