apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: supabase-operator
  newName: code.icb4dc0.de/prskr/supabase-operator
  newTag: 0.0.0-SNAPSHOT-03270ec

resources:
- ../../default
