apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: controller
    newName: ghcr.io/prskr/supabase-operator/controller
    newTag: 0.1.0-SNAPSHOT-e6c7d68
resources:
  - ../../crd
  - ../../default
