---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - supabase.k8s.icb4dc0.de
  resources:
  - cores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - supabase.k8s.icb4dc0.de
  resources:
  - cores/finalizers
  verbs:
  - update
- apiGroups:
  - supabase.k8s.icb4dc0.de
  resources:
  - cores/status
  verbs:
  - get
  - patch
  - update
