---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - supabase.k8s.icb4dc0.de
  resources:
  - apigateways
  - cores
  - dashboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - supabase.k8s.icb4dc0.de
  resources:
  - apigateways/finalizers
  - cores/finalizers
  - dashboards/finalizers
  verbs:
  - update
- apiGroups:
  - supabase.k8s.icb4dc0.de
  resources:
  - apigateways/status
  - cores/status
  - dashboards/status
  verbs:
  - get
  - patch
  - update
