apiVersion: v1
kind: Secret
metadata:
  name: supabase-demo-credentials
stringData:
  url: postgresql://supabase_admin:1n1t-R00t!@cluster-example-rw.supabase-demo:5432/app
---
apiVersion: supabase.k8s.icb4dc0.de/v1alpha1
kind: Core
metadata:
  labels:
    app.kubernetes.io/name: supabase-operator
    app.kubernetes.io/managed-by: kustomize
  name: core-sample
spec:
  database:
    dsnFrom:
      name: supabase-demo-credentials
      key: url
  auth:
    externalUrl: http://localhost:8000/
    siteUrl: http://localhost:3000/
    disableSignup: true
    enableEmailAutoconfirm: true
    providers: {}
