apiVersion: supabase.k8s.icb4dc0.de/v1alpha1
kind: Core
metadata:
  name: core-sample
  labels:
    app.kubernetes.io/name: supabase-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  # public URL of the Supabase instance (API)
  # normally the Ingress/HTTPRoute endpoint
  externalUrl: http://localhost:8000/
  # public URL of the frontend
  # could be the same as the externalUrl if you're using one Ingress/HTTPRoute for both
  # or a different one if you prefer to separate API and frontend URLs
  # will be used by Supabase Auth to redirect users after login
  siteUrl: http://localhost:3000/
  database:
    dsnSecretRef:
      # name of the secret containing the database DSN
      name: supabase-demo-credentials
      key: url
  auth:
    enableEmailAutoconfirm: true
    providers: {}
  postgrest:
    maxRows: 1000
  jwt:
    expiry: 3600
    # name of the secret containing the JWT secret
    # will be created if not found, make sure to refernce this secret in:
    # - APIGateway
    # - Dashboard-
    # - Storage
    secretName: core-sample-jwt
