apiVersion: supabase.k8s.icb4dc0.de/v1alpha1
kind: Storage
metadata:
  labels:
    app.kubernetes.io/name: supabase-operator
    app.kubernetes.io/managed-by: kustomize
  name: core-sample
spec:
  backendType: file
  db:
    host: cluster-example-rw.supabase-demo.svc
    dbName: app
    dbCredentialsRef:
      secretName: core-sample-db-creds-supabase-storage-admin
  enableImageTransformation: true
  jwtAuth:
    secretName: core-sample-jwt
