load("@rules_go//go:def.bzl", "go_library")

filegroup(
    name = "api-types",
    srcs = glob([
        "*_types.go",
    ]) + ["groupversion_info.go"],
    visibility = ["//:__subpackages__"],
)

go_library(
    name = "v1alpha1",
    srcs = [
        "apigateway_types.go",
        "common_types.go",
        "core_types.go",
        "dashboard_types.go",
        "groupversion_info.go",
        "storage_types.go",
        "zz_generated.deepcopy.go",
    ],
    importpath = "github.com/prskr/supabase-operator/api/v1alpha1",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/supabase",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/api/resource",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_apimachinery//pkg/types",
        "@io_k8s_sigs_controller_runtime//pkg/client",
        "@io_k8s_sigs_controller_runtime//pkg/scheme",
    ],
)
