apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-system

resources:
  - namespace.yaml
  - rbac/serviceaccount.yaml
  - rbac/clusterrole.yaml
  - rbac/clusterrolebinding.yaml
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.84.1/bundle.yaml
  - prometheus.yaml
