load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@rules_go//go:def.bzl", "go_library")
load("//:versions.bzl", "ENVOY_REPO", "ENVOY_TAG")

genrule(
    name = "supabase-images",
    srcs = [
        "@supabase_compose//:docker-compose",
    ],
    outs = ["images.go"],
    cmd = """
        $(execpath //tools/codegen/images:images) \
            -source-file=$(location @supabase_compose//:docker-compose) \
            -out-file=$@ \
            -envoy-repo={} \
            -envoy-tag={}
    """.format(ENVOY_REPO, ENVOY_TAG),
    tools = [
        "//tools/codegen/images",
    ],
)

write_source_files(
    name = "generate",
    diff_test = False,
    files = {
        # Destination in source tree : Source from Bazel output
        "images.go": ":supabase-images",
    },
)

go_library(
    name = "supabase",
    srcs = [
        "auth.go",
        "db_roles.go",
        "env.go",
        "env_types.go",
        "envoy.go",
        "images.go",
        "img_proxy.go",
        "jwt.go",
        "pg_meta.go",
        "postgrest.go",
        "storage.go",
        "studio.go",
    ],
    importpath = "github.com/prskr/supabase-operator/internal/supabase",
    visibility = ["//:__subpackages__"],
    deps = [
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@org_golang_x_exp//constraints",
    ],
)
