<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>supabase_integration.api_test</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Supabase" Version="1.1.1" />
    <PackageReference Include="TUnit" Version="0.6.123" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.13.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="TUnit.Core" />
  </ItemGroup>

</Project>
