apiVersion: supabase.k8s.icb4dc0.de/v1alpha1
kind: APIGateway
metadata:
  labels:
    app.kubernetes.io/name: supabase-operator
    app.kubernetes.io/managed-by: kustomize
  name: gateway-sample
  namespace: supabase-demo
spec:
  envoy:
    disableIPv6: true
    workloadSpec:
      replicas: 1
  apiEndpoint:
    jwks:
      name: core-sample-jwt
      key: jwks.json
  dashboardEndpoint:
    tls:
      cert:
        secretName: dashboard-tls-cert
    auth:
      # basic:
      #   plaintextUsersSecretRef: studio-sample-basic-auth
      oauth2:
        openIdIssuer: "http://studio-idp:5556"
        clientId: 3a33e68a-c30d-4110-b4e9-bf5d45ab2126
        scopes:
          - openid
          - profile
          - email
        clientSecretRef:
          name: studio-sample-oauth2
          key: clientSecret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: dashboard-tls
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: supabase-operator
    app.kubernetes.io/part-of: supabase-operator
    app.kubernetes.io/managed-by: kustomize
  name: dashboard-tls
  namespace: supabase-demo
spec:
  dnsNames:
    - gateway-sample-envoy.supabase-demo.svc
    - gateway-sample-envoy.supabase-demo.svc.cluster.local
    - localhost:3000
  issuerRef:
    kind: ClusterIssuer
    name: cluster-pki
  secretName: dashboard-tls-cert
