apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.3/cert-manager.yaml
  - https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.25.0/cnpg-1.25.0.yaml
  - resources/minio.yaml
  - ../default

patches:
  - path: manager_dev_settings.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/name=supabase-operator
  - path: manager_dev_settings.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/name=control-plane
