---
apiVersion: v1
kind: Secret
metadata:
  name: storage-s3-credentials
  namespace: supabase-demo
stringData:
  accessKeyId: FPxTAFL7NaubjPgIGBo3
  secretAccessKey: 7F437pPe84QcoocD3MWdAIVBU3oXonhVHxK645tm
---
apiVersion: supabase.k8s.icb4dc0.de/v1alpha1
kind: Storage
metadata:
  labels:
    app.kubernetes.io/name: supabase-operator
    app.kubernetes.io/managed-by: kustomize
  name: storage-sample
  namespace: supabase-demo
spec:
  api:
    s3Backend:
      endpoint: http://minio.minio-dev.svc:9000
      region: us-east-1
      forcePathStyle: true
      bucket: test
      credentialsSecretRef:
        secretName: storage-s3-credentials
    s3: {}
    db:
      host: cluster-example-rw.supabase-demo.svc
      dbName: app
      dbCredentialsRef:
        # will be created by Core resource operator if not present
        # just make sure the secret name is either based on the name of the core resource or explicitly set
        # format <core-resource-name>-db-creds-supabase-storage-admin
        secretName: core-sample-db-creds-supabase-storage-admin
    jwtAuth:
      # will be created by Core resource operator if not present
      # just make sure the secret name is either based on the name of the core resource or explicitly set
      secretName: core-sample-jwt
  imageProxy:
    enable: true
