apiVersion: v1
kind: Service
metadata:
  name: control-plane
  namespace: supabase-system
  labels:
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
    - name: grpc
      port: 18000
      protocol: TCP
      targetPort: 18000
  selector:
    app.kubernetes.io/name: control-plane
