apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: seaweedfs
  name: seaweedfs
  namespace: seaweedfs
spec:
  serviceName: seaweedfs
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seaweedfs
    spec:
      containers:
        - name: seaweedfs
          image: seaweedfs
          args:
            - mini
            - -dir=/data
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: accessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secretAccessKey
          ports:
            - name: s3
              containerPort: 8333
            - name: admin
              containerPort: 23646
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
