load("@bazel_env.bzl", "bazel_env")
load("@gazelle//:go_tools.bzl", "GO_TOOLS")

package(default_visibility = ["//visibility:public"])

bazel_env(
    name = "bazel_env",
    toolchains = {},
    tools = {
        # Tools can be specified as labels.
        "buildifier": "@buildifier_prebuilt//:buildifier",
        "gazelle": "//:gazelle",
        "go": "@rules_go//go",
        "hugo": "@multitool//tools/hugo:hugo",
        "kubectl": "@multitool//tools/kubectl:kubectl",
    } | GO_TOOLS,
)
