load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "api",
    srcs = ["common.go"],
    importpath = "github.com/prskr/supabase-operator/api",
    visibility = ["//visibility:public"],
    deps = [
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_sigs_controller_runtime//pkg/client",
    ],
)
