name: Docs
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: "true"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install python packages
        run: pip install -r requirements.txt

      - name: Build the website
        run: mkdocs build

      - name: Copy files to the s3 website content bucket
        # for the time being, let's just always deploy the docs
        # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: rclone sync site/ HCLOUD:/1661580-supabase-operator-docs/
        env:
          RCLONE_CONFIG_HCLOUD_TYPE: s3
          RCLONE_CONFIG_HCLOUD_PROVIDER: Other
          RCLONE_CONFIG_HCLOUD_ACCESS_KEY_ID: ${{ secrets.HCLOUD_KEY_ID }}
          RCLONE_CONFIG_HCLOUD_SECRET_ACCESS_KEY: ${{ secrets.HCLOUD_SECRET_KEY }}
          RCLONE_CONFIG_HCLOUD_ENDPOINT: ${{ secrets.HCLOUD_ENDPOINT }}
          RCLONE_CONFIG_HCLOUD_REGION: hel1
