name: Go
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: registry.icb4dc0.de
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Build images
        run: bazel run --bazelrc=.github/workflows/ci.bazelrc //:image_multiarch

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        if: github.ref_type == 'tag'
        with:
          config: cliff.toml
          args: --current
        env:
          OUTPUT: release-notes.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Release
        if: github.ref_type == 'tag'
        run: |
          tea login add --url ${{ env.GITHUB_SERVER_URL }}
          bazel run --bazelrc=.github/workflows/ci.bazelrc //:push

          mkdir release
          sh -c "cd config/release/default && kustomize edit set image supabase-operator=registry.icb4dc0.de/supabase-operator/controller:{{ github.ref_name }}"
          kustomize build config/release/default > release/operator_manifest.yaml

          tea release create \
            --title "${{ github.ref_name }}" \
            --note-file release-notes.md \
            --repo ${{ github.repository }} \
            --asset release/operator_manifest.yaml
        env:
          GITEA_SERVER_TOKEN: ${{ secrets.RELEASE_TOKEN }}
