name: Build & Release
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
permissions:
  contents: write
  packages: write
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          cache-save: ${{ github.event_name != 'pull_request' }}
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
          fetch-tags: 'true'
      - name: Build app and images
        run: |
          bazel --bazelrc=.github/workflows/ci.bazelrc test //... --test_env "KUBEBUILDER_ASSETS=$(bazel --bazelrc=.github/workflows/ci.bazelrc run --run_in_cwd @io_k8s_sigs_controller_runtime_tools_setup_envtest//:setup-envtest -- use -p path)" || true
          bazel --bazelrc=.github/workflows/ci.bazelrc build //:image_multiarch
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        if: github.ref_type == 'tag'
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        if: github.ref_type == 'tag'
        id: git-cliff
        with:
          config: cliff.toml
          args: --current
        env:
          OUTPUT: CHANGELOG.md
      - name: Release
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Pushing image..."
          bazel --bazelrc=.github/workflows/ci.bazelrc run //:push

          mkdir release
          echo "Setting controller image to ghcr.io/prskr/supabase-operator/controller:${GITHUB_REF_NAME#v}"
          sh -c "cd config/release/default && kustomize edit set image controller=ghcr.io/prskr/supabase-operator/controller:${GITHUB_REF_NAME#v}"
          kustomize build config/release/default > release/operator_manifest.yaml

          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --notes-file ${{ steps.git-cliff.outputs.changelog }} \
            release/operator_manifest.yaml
