name: Postgres image
on:
  schedule:
    # every Thursday 2:30am
    - cron: '30 2 * * 2'
  push:
    paths:
      - .github/workflows/postgres.yml
      - postgres/**
    branches:
      - main
    tags:
      - 'v*'

env:
  MINOR_VERSIONS: '{"15":"14","17":"5"}'

jobs:
  build:
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
        postgres_major:
          - '15'
          - '17'
    runs-on: fedora-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v5

      - name: Login to Harbor
        uses: redhat-actions/podman-login@v1
        with:
          registry: registry.icb4dc0.de
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            postgres/Dockerfile
          image: registry.icb4dc0.de/supabase-operator/postgres
          tags: ${{ matrix.postgres_major }}.${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }}.${{ github.run_number }}-${{ matrix.arch }}
          build-args: |
            POSTGRES_MAJOR=${{ matrix.postgres_major }}
            POSTGRES_MINOR=${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }}

      - name: Push to Harbor
        run: |
          podman push ${{ steps.build-image.outputs.image }}:${{ steps.build-image.outputs.tags }}

  manifest:
    strategy:
      matrix:
        postgres_major:
          - '15'
          - '17'
    runs-on: fedora
    needs:
      - build
    steps:
      - name: Login to Harbor
        uses: redhat-actions/podman-login@v1
        with:
          registry: registry.icb4dc0.de
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Create manifest
        run: |
          buildah manifest create \
              registry.icb4dc0.de/supabase-operator/postgres:${{ matrix.postgres_major }}.${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }} \
              registry.icb4dc0.de/supabase-operator/postgres:${{ matrix.postgres_major }}.${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }}.${{ github.run_number }}-arm64 \
              registry.icb4dc0.de/supabase-operator/postgres:${{ matrix.postgres_major }}.${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }}.${{ github.run_number }}-amd64

          buildah tag \
              registry.icb4dc0.de/supabase-operator/postgres:${{ matrix.postgres_major }}.${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }} \
              registry.icb4dc0.de/supabase-operator/postgres:${{ matrix.postgres_major }}.${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }}.${{ github.run_number }}

          buildah manifest push --all registry.icb4dc0.de/supabase-operator/postgres:${{ matrix.postgres_major }}.${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }}
          buildah manifest push --all registry.icb4dc0.de/supabase-operator/postgres:${{ matrix.postgres_major }}.${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }}.${{ github.run_number }}

          skopeo delete docker://registry.icb4dc0.de/supabase-operator/postgres:${{ matrix.postgres_major }}.${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }}.${{ github.run_number }}-arm64
          skopeo delete docker://registry.icb4dc0.de/supabase-operator/postgres:${{ matrix.postgres_major }}.${{ fromJSON(env.MINOR_VERSIONS)[matrix.postgres_major] }}.${{ github.run_number }}-amd64
